export const SET_CHECKOUT = 'SET_CHECKOUT';
export const LOAD_ITEMS = 'LOAD_ITEMS';
export const SET_ITEM_ID_IN_PREVIEW = 'SET_ITEM_ID_IN_PREVIEW';
export const ADD_PRODUCT_ITEM = 'ADD_PRODUCT_ITEM';
export const SUBSTRACT_PRODUCT_ITEM = 'SUBSTRACT_PRODUCT_ITEM';
export const REMOVE_ALL_SHOPING_CART_ITEMS = 'REMOVE_ALL_SHOPING_CART_ITEMS';
export const LOAD_SHOPPING_CART = 'LOAD_SHOPPING_CART';

